# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PEMADO
email: martina@pemado.com
description: "Ručně vyráběné svíčky, podpalovače z dřevité vlny a ruční pochodně."
tagline: "Ručně vyráběné svíčky, podpalovače z dřevité vlny a ruční pochodně."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pemado.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lukas-bednar
repository: "lukas-bednar/pemado-web"

# Analytics
analytics:
  provider: google-gtag  # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: G-GTW9RG9W8K
    anonymize_ip: false # true, false (default)

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll
# air  contrast default mint  plum
# aqua dark     dirt    neon  sunrise
#minimal_mistakes_skin: default
minimal_mistakes_skin: contrast
locale: cs-CZ
date_format: "%d.%m.%Y"
search: true
breadcrumbs: false
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
include:
  - _pages
  - _products
#  - _posts

collections:
  products:
    output: true
#  posts:
#    output: true


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#masthead_title: " "
logo: "/assets/images/logo2.png"

defaults:
  # All pages
  - scope:
      path: ""
    values:
      layout: single
      header:
        overlay_filter: "0.15"
        overlay_image: /assets/images/overlay.jpg
