- name: Rustikální Svíčky
  image: /assets/images/rustic.jpg
  description: A handmade rustic candle perfect for a cozy atmosphere.

- name: Ručně Malované Svíčky
  image: /assets/images/malovane-s.jpg
  description: Infused with natural essential oils for a relaxing experience.

- name: Venkovní Svíčky
  image: /assets/images/outdoor.jpg
  description: Large, wind-resistant candle ideal for gardens and patios.

- name: Podpalovače
  image: /assets/images/podpalovace.jpg
  description: A decorative candle with a festive scent for special occasions.

- name: Pochodně
  image: /assets/images/pochodne.jpg
  description: A decorative candle with a festive scent for special occasions.

